name: Backend CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Ordinalnovus image
        run: |
          TAG_NAME="latest"
          MONGODB_STRING=$MONGODB_URI
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            TAG_NAME="dev"
            MONGODB_STRING="mongodb://ordinalnovus_dev:xERD56_gth@192.168.1.33:27017/ordinalnovus_dev?retryWrites=true&w=majority&authMechanism=DEFAULT"
          fi
          docker build -t crypticmetadev/ordinalnovus:$TAG_NAME . \
            --build-arg MONGODB_URI=$MONGODB_STRING

      - name: Log in to Docker registry
        run: docker login -u crypticmetadev -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push ordinalnovus image to Docker registry
        run: |
          TAG_NAME="latest"
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            TAG_NAME="dev"
          fi
          docker push crypticmetadev/ordinalnovus:$TAG_NAME
