name: Ordinalnovus CI

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push-ordinalnovus:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Ordinalnovus image
        run: |
          TAG_NAME="latest"
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            TAG_NAME="dev"
          fi
          docker build -t crypticmetadev/ordinalnovus:$TAG_NAME .

      - name: Log in to Docker registry
        run: docker login -u crypticmetadev -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push ordinalnovus image to Docker registry
        run: |
          TAG_NAME="latest"
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            TAG_NAME="dev"
          fi
          docker push crypticmetadev/ordinalnovus:$TAG_NAME
